name: OnlineTime
main: Dready\OnlineTime\Main
version: 1.0
api: 3.0.0
author: Dready
description: Measure time spent online

commands:
 onlinetime:
  aliases: [ot, otime]
  description: "View how much time you've spent on the server"
  permission: onlinetime

permissions:
 reset.onlinetime:
  default: op
  description: "reset"
 onlinetime:
  default: true
  description: "ot"
